# Generated by Django 6.0.6 on 2026-07-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='status',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video',
            name='added_at',
        ),
        migrations.AddField(
            model_name='match',
            name='away_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='home_logo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
