# Generated by Django 6.0.6 on 2026-07-11 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_remove_analysis_created_at_remove_analysis_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 7, 11, 21, 8, 37, 699121, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysis',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
