# Generated by Django 5.1.3 on 2026-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0003_analysis_created_at_analysis_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
