# Generated by Django 6.0.6 on 2026-07-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0004_alter_analysis_id_alter_match_id_alter_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
