# Generated by Django 6.0.6 on 2026-07-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sports", "0006_alter_analysis_id_alter_match_id_alter_video_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="away_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="home_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="match",
            name="status",
            field=models.CharField(default="SCHEDULED", max_length=20),
        ),
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="away_team",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_logo",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="match",
            name="home_team",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="match",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="match",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="videos",
                to="sports.match",
            ),
        ),
    ]
